Repository WildCodeSchool/202302-orleans-php-project-externatic, pull requests merged in 2023-06, with the labels that each got.

#2 initialisation
  assets/app.js
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: REVIEWED, CORRECTIONS DONE

#4 Footer DONE
  assets/images/instagram.svg
  assets/images/linkedin.svg
  assets/images/twitter.svg
  assets/styles/app.scss
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#5 modifs footer fixed and font-size
  templates/components/_footer.html.twig
Labels: REVIEWED

#6 mentions légales
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/mentionsLegales.html.twig
Labels: REVIEWED

#11 S0 consultant crud
  composer.json
  composer.lock
  src/Controller/ConsultantController.php
  src/DataFixtures/ConsultantFixtures.php
  src/Entity/Consultant.php
  src/Form/ConsultantType.php
  src/Repository/ConsultantRepository.php
  templates/consultant/_delete_form.html.twig
  templates/consultant/_form.html.twig
  templates/consultant/edit.html.twig
  templates/consultant/index.html.twig
  templates/consultant/new.html.twig
  templates/icons/edit.svg
  templates/icons/new.svg
Labels: REVIEWED

#12 navbar admin
  assets/styles/admin/_navbar-admin.scss
  templates/components/admin/_navbar-admin.html.twig
  webpack.config.js
Labels: REVIEWED

#15 fix homepage
  assets/images/durabilitee.svg
  templates/home/index.html.twig
Labels: REVIEWED

#17 modifs crud new-consultant
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Entity/Consultant.php
  src/Form/ConsultantType.php
  symfony.lock
  templates/admin-template.html.twig
  templates/consultant/_form.html.twig
  templates/consultant/edit.html.twig
  templates/consultant/new.html.twig
  templates/icons/return.svg
  templates/icons/save.svg
Labels: REVIEWED

#19 modifs nav-admin
  templates/admin-template.html.twig
  templates/components/admin/_navbar-admin.html.twig
  templates/consultant/index.html.twig
  templates/consultant/new.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#18 modifs crud delete a consultant
  templates/consultant/_delete_form.html.twig
  templates/icons/delete.svg
Labels: REVIEWED

#16 S02 connexion
  assets/images/id_logo.svg
  assets/images/id_pic.png
  assets/images/mdp_logo.svg
  config/packages/security.yaml
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  templates/icons/identifiant.svg
  templates/icons/password.svg
  templates/login/index.html.twig
Labels: REVIEWED

#21 modifs edit consultant
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Entity/Consultant.php
Labels: REVIEWED

#22 correction d'une faute de frappe
  templates/icons/identifiant.svg
Labels: REVIEWED

#24 Gestion du logout
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  src/Controller/LoginController.php
  symfony.lock
  templates/components/_navbar.html.twig
Labels: REVIEWED

#23 Consultant on homepage
  assets/images/linkedin-home.png
  assets/images/linkedin-home.svg
  assets/images/placeholder-consultant.jpeg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  composer.lock
  src/Controller/HomeController.php
  templates/components/_footer.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#26 page create job offer
  src/Controller/AdminJobOfferController.php
  src/Controller/JobOfferController.php
  src/Form/JobOfferType.php
  templates/JobOffer/index.html.twig
  templates/admin_jobOffer/_delete_form.html.twig
  templates/admin_jobOffer/_form.html.twig
  templates/admin_jobOffer/edit.html.twig
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/new.html.twig
  templates/admin_jobOffer/show.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#37 modifs read crud company
  templates/company/show.html.twig
Labels: REVIEWED

#39 delete crud company
  templates/company/_delete_form.html.twig
Labels: REVIEWED

#38 edit crud company
  config/packages/vich_uploader.yaml
  src/Entity/Company.php
  src/Form/CompanyType.php
  templates/company/_form.html.twig
  templates/company/edit.html.twig
Labels: REVIEWED

#40 modifs new company
  templates/company/new.html.twig
Labels: REVIEWED

#41 modif carousel
  templates/home/index.html.twig
Labels: REVIEWED, RUBEN'S LABEL

#42 page edit bouton delete
  templates/admin_jobOffer/_delete_form.html.twig
Labels: REVIEWED

#44 Fix Fixtures
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/Candidate/show.html.twig
Labels: REVIEWED, RUBEN'S LABEL

#43 page list des offres d'emlpoi
  assets/styles/_navbar-admin.scss
  templates/admin_jobOffer/index.html.twig
  templates/components/admin/_navbar-admin.html.twig
  templates/icons/edit.svg
  templates/icons/view.svg
Labels: REVIEWED, RUBEN'S LABEL

#53 modifs logo colors
  assets/images/instagram.svg
  assets/images/linkedin.svg
  assets/images/twitter.svg
  templates/components/_footer.html.twig
Labels: REVIEWED

#52 Business card
  assets/images/technology.jpg
  src/Controller/BusinessCardController.php
  src/DataFixtures/BusinessCardFixtures.php
  src/Entity/BusinessCard.php
  src/Repository/BusinessRepository.php
  templates/business-card/index.html.twig
Labels: REVIEWED

#56 modifs link
  src/Controller/BusinessCardController.php
  templates/components/_navbar.html.twig
Labels: REVIEWED

#58 fix
  migrations/Version20230621084012.php
Labels: REVIEWED

#59 modifs
  migrations/Version20230621090302.php
Labels: REVIEWED

#60 Fix candidateFixtures
  src/DataFixtures/UserFixtures.php
Labels: REVIEWED

#57 S02 add formation
  composer.lock
  config/packages/translation.yaml
  migrations/Version20230606100812.php
  migrations/Version20230615134737.php
  migrations/Version20230620121334.php
  src/Controller/CandidateController.php
  src/DataFixtures/FormationFixture.php
  src/Entity/Formation.php
  src/Form/FormationType.php
  src/Repository/FormationRepository.php
  templates/candidate/edit.html.twig
  templates/candidate/show.html.twig
  templates/formation/_form.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#63 Fix.migration
  migrations/Version20230621084012.php
  migrations/Version20230621090302.php
  migrations/Version20230622083925.php
Labels: REVIEWED, RUBEN'S LABEL

#64 Final.company.home
  assets/images/FAQ.jpg
  assets/images/acceder.jpg
  assets/images/fonctionnement.jpg
  assets/images/methode.jpg
  assets/images/optimiser.jpg
  assets/images/recrutement.jpg
  assets/styles/pagecompany.scss
  migrations/Version20230621141110.php
  src/Controller/CompanyHomeController.php
  templates/company/home/index.html.twig
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: REVIEWED

#66 modif footer
  assets/images/instagram.svg
  assets/images/linkedin.svg
  assets/images/twitter.svg
  templates/components/_footer.html.twig
Labels: REVIEWED, RUBEN'S LABEL

#70 modifs little
  assets/styles/home.scss
  assets/styles/login.scss
  templates/home/index.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: REVIEWED

#67 modifs all admin
  assets/images/admin.jpg
  src/Controller/HomeAdminController.php
  templates/admin-template.html.twig
  templates/base-admin.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/components/admin/_navbar-admin.html.twig
  templates/components/admin/home.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/consultant/edit.html.twig
  templates/consultant/index.html.twig
  templates/consultant/new.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#73 modifs
  templates/admin_jobOffer/edit.html.twig
  templates/admin_jobOffer/index.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/consultant/index.html.twig
Labels: REVIEWED

#75 S03 add favorite offer
  assets/app.js
  config/packages/security.yaml
  migrations/Version20230621122932.php
  migrations/Version20230622083609.php
  migrations/Version20230622091002.php
  src/Controller/JobOfferController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/JobOffer.php
  src/Entity/User.php
  templates/jobOffer/_favorite_form.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#62 page candidate avec statistiques - info -FAQ
  assets/images/FAQ.png
  assets/images/candidat/acces_reseaux.jpeg
  assets/images/candidat/contrat_signer.jpeg
  assets/images/candidat/psychologue.jpeg
  assets/images/candidat/temps_rolex.jpeg
  assets/images/candidat/videoconference.jpeg
  assets/styles/pageCandidate.scss
  assets/styles/variables.scss
  src/Controller/PageCandidateController.php
  templates/PageCandidate/index.html.twig
  webpack.config.js
Labels: REVIEWED, CONFLICTS RESOLVED

#79 dropdown
  assets/app.js
  templates/components/_navbar.html.twig
Labels: REVIEWED

#80 S04 candidate profile
  migrations/Version20230624114353.php
  migrations/Version20230624115322.php
  migrations/Version20230624121425.php
  migrations/Version20230624124826.php
  migrations/Version20230624152147.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/FormationFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/Experience.php
  src/Entity/Formation.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Repository/ExperienceRepository.php
  src/Repository/SkillRepository.php
  templates/candidate/show.html.twig
  templates/icons/arrow.svg
Labels: REVIEWED, CONFLICTS RESOLVED

#83 modifs navbar link
  migrations/Version20230626145425.php
  src/Controller/PageCandidateController.php
  templates/components/_navbar.html.twig
Labels: REVIEWED

#86 modifs background color on candidate page
  assets/styles/pageCandidate.scss
  assets/styles/variables.scss
Labels: REVIEWED

#87 modifs link in business card page
  templates/business-card/index.html.twig
Labels: REVIEWED

#89 modif d'une route
  templates/candidate/show.html.twig
Labels: REVIEWED

#90 modifs svg
  assets/images/durabilitee.svg
  assets/images/evenement.svg
  assets/images/performance.svg
  assets/images/proximitee.svg
Labels: REVIEWED

#91 fix
  src/Controller/CandidateController.php
Labels: REVIEWED
