Repository WildCodeSchool/202302-orleans-php-project-externatic, pull requests merged in 2023-07, with the labels that each got.

#94 S04 candidate delete experience
  src/Controller/CandidateController.php
  templates/candidate/show.html.twig
  templates/experience/_delete_form.html.twig
Labels: REVIEWED

#99 fix btn
  src/Controller/HomeController.php
  src/Controller/JobOfferController.php
  templates/components/_navbar.html.twig
Labels: REVIEWED

#100 candidate delete formation
  src/Controller/CandidateController.php
  templates/candidate/show.html.twig
  templates/formation/_delete_form.html.twig
Labels: REVIEWED

#96 supprimer un skill as a candidate
  src/Controller/CandidateController.php
  templates/icons/trash.svg
  templates/skill/_delete_form.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#97 candidate add experience
  src/Controller/CandidateController.php
  src/Form/ExperienceType.php
  templates/candidate/show.html.twig
  templates/experience/_form.html.twig
  templates/experience/add.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#101 S04 candidate add skill
  composer.lock
  src/Controller/CandidateController.php
  src/Form/SkillType.php
  templates/candidate/show.html.twig
  templates/skill/_form.html.twig
  templates/skill/add.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#104 fix experience delete
  src/Controller/CandidateController.php
Labels: REVIEWED

#103 modif route
  src/Controller/CandidateController.php
Labels: REVIEWED

#105 fix methods add
  src/Controller/CandidateController.php
Labels: REVIEWED

#102 ajout d'une fonction disparue
  src/Controller/CandidateController.php
Labels: REVIEWED, CONFLICTS RESOLVED

#82 barre de recherche job
  assets/images/FAQ.png
  assets/images/admin.jpg
  assets/styles/jobOffer.scss
  src/Controller/JobOfferController.php
  src/DataFixtures/JobOfferFixtures.php
  src/Form/SearchJobType.php
  src/Repository/JobOfferRepository.php
  templates/company/home/index.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#107 Fix skill supp
  templates/candidate/show.html.twig
Labels: REVIEWED, CORRECTIONS DONE

#106 Fix nav
  package-lock.json
  src/Controller/CandidateController.php
  templates/candidate/_form.html.twig
  templates/candidate/profile.html.twig
  templates/components/_navbar.html.twig
  yarn.lock
Labels: CONFLICTS

#109 fix jobOfferFixtures
  src/DataFixtures/JobOfferFixtures.php
Labels: REVIEWED

#112 Style profil
  assets/images/profil-user.png
  assets/styles/profil.scss
  templates/candidate/edit.html.twig
  templates/candidate/profile.html.twig
  templates/experience/_delete_form.html.twig
  templates/experience/_form.html.twig
  templates/experience/add.html.twig
  templates/formation/_form.html.twig
  templates/formation/edit.html.twig
  templates/skill/_form.html.twig
  templates/skill/add.html.twig
  webpack.config.js
Labels: REVIEWED, CONFLICTS RESOLVED

#114 modifs style register
  assets/images/register.png
  assets/styles/register.scss
  templates/components/_navbar.html.twig
  templates/icons/email.svg
  templates/icons/identifiant1.svg
  templates/icons/password1.svg
  templates/jobOffer/_favorite_form.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: REVIEWED, CONFLICTS RESOLVED

#115 fix des render
  src/Controller/CandidateController.php
Labels: REVIEWED

#113 candidate edit profile
  src/Controller/CandidateController.php
  src/Entity/User.php
  src/Form/CandidateType.php
  templates/candidate/_form.html.twig
  templates/candidate/show.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#121 modifs style business card
  templates/business-card/index.html.twig
Labels: REVIEWED

#118 Fix button relocation
  templates/bundles/TwigBundle/Exception/error300.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: REVIEWED

#116 modifs style candidate
  src/Controller/PageCandidateController.php
  templates/PageCandidate/index.html.twig
Labels: REVIEWED

#122 Fix size webp
  assets/images/Bernie_pelle.webp
  assets/images/Buster_smile.webp
  assets/images/Holy_Grail_403.webp
  assets/images/Marx_bro_dig.webp
  templates/bundles/TwigBundle/Exception/error300.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: REVIEWED

#120 favorite-page
  src/Controller/FavoriteController.php
  templates/components/_navbar.html.twig
  templates/components/jobOffer-card.html.twig
  templates/favourite/index.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#119 S04 candidate profile pic upload
  config/packages/vich_uploader.yaml
  migrations/Version20230705091015.php
  src/Controller/CandidateController.php
  src/Entity/Candidate.php
  src/Form/ProfilePicType.php
  templates/candidate/edit_profilePic.html.twig
  templates/candidate/profile.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#124 modifs style profil
  templates/candidate/_form.html.twig
  templates/candidate/edit_profilePic.html.twig
  templates/candidate/profile.html.twig
  templates/candidate/show.html.twig
  templates/experience/_form.html.twig
  templates/formation/_delete_form.html.twig
  templates/formation/_form.html.twig
  templates/skill/_form.html.twig
Labels: REVIEWED

#126 modifs message false identifiants
  templates/candidate/show.html.twig
  templates/login/index.html.twig
Labels: REVIEWED

#125 modifs style candidat to company
  src/Controller/CandidateController.php
  templates/candidate/show.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#128 fix style register...
  assets/app.js
  src/Form/RegistrationFormType.php
  templates/components/_navbar.html.twig
Labels: REVIEWED

#133 Dev to main Semaine 5
  assets/app.js
  assets/styles/jobOffer.scss
  composer.json
  composer.lock
  migrations/Version20230706080402.php
  migrations/Version20230706091318.php
  src/Controller/AdminJobOfferController.php
  src/Controller/CandidateController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/Candidate.php
  src/Entity/JobOffer.php
  src/Form/JobOfferType.php
  src/Form/RegistrationFormType.php
  src/Service/DistanceCalculator.php
  src/Service/Localizable.php
  src/Service/Locator.php
  templates/admin_jobOffer/index.html.twig
  templates/candidate/_form.html.twig
  templates/candidate/edit_profilePic.html.twig
  templates/candidate/profile.html.twig
  templates/candidate/show.html.twig
  templates/components/_navbar.html.twig
  templates/components/jobOffer-card.html.twig
  templates/experience/_form.html.twig
  templates/formation/_delete_form.html.twig
  templates/formation/_form.html.twig
  templates/jobOffer/index.html.twig
  templates/login/index.html.twig
  templates/skill/_form.html.twig
Labels: REVIEWED

#127 New s04 #41
  assets/controllers.json
  assets/images/backgroundCardExternatic10.png
  assets/images/backgroundCardExternatic11.png
  assets/images/backgroundCardExternatic21.png
  assets/images/jobOffercardfooter.jpg
  assets/styles/adminConsultant.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20230626085125.php
  package.json
  src/Controller/AdminConsultantController.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/JobOffer.php
  src/Repository/JobOfferRepository.php
  symfony.lock
  templates/admin_consultant/index.html.twig
  templates/components/_navbar.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/icons/contract.svg
  templates/icons/location.svg
  templates/icons/people.svg
  templates/jobOffer/index.html.twig
  webpack.config.js
  yarn.lock
Labels: REVIEWED, CONFLICTS RESOLVED

#131 modifs
  assets/styles/login.scss
  assets/styles/register.scss
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: REVIEWED

#134 Add localization Offer
  migrations/Version20230706091318.php
  migrations/Version20230706152922.php
  src/Controller/CandidateController.php
  src/DataFixtures/CandidateFixtures.php
  src/Entity/Candidate.php
  src/Entity/JobOffer.php
  src/Service/Locator.php
Labels: REVIEWED

#138 buttons delete skill
  templates/candidate/profile.html.twig
Labels: REVIEWED

#139 modif du style de la scrollbar des cards sombres
  assets/styles/adminConsultant.scss
  assets/styles/variables.scss
  templates/admin_consultant/index.html.twig
  templates/icons/see.svg
Labels: REVIEWED

#140 modifs admin page
  assets/images/admin.jpg
  migrations/Version20230624124826.php
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/components/_navbar.html.twig
  templates/components/admin/home.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/consultant/edit.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#141 Map
  .eslintignore
  assets/controllers/map_controller.js
  assets/styles/jobOffer.scss
  package.json
  src/Controller/AdminJobOfferController.php
  src/Form/JobOfferType.php
  templates/admin_jobOffer/show.html.twig
  templates/jobOffer/index.html.twig
  yarn.lock
Labels: REVIEWED

#142 modifs delete competence
  templates/candidate/profile.html.twig
Labels: REVIEWED

#143 supp tous droits réservés
  templates/components/_footer.html.twig
Labels: REVIEWED

#144 Fix config https prod
  config/packages/framework.yaml
  src/Controller/AdminJobOfferController.php
  src/Controller/RegistrationController.php
  templates/login/index.html.twig
Labels: REVIEWED

#145 modifs style carte
  assets/styles/jobOffer.scss
  src/Form/SearchJobType.php
  templates/components/_navbar.html.twig
  templates/components/jobOffer-card.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#146 filtrage des offres d'emploi search
  assets/controllers.json
  assets/styles/adminConsultant.scss
  composer.json
  composer.lock
  config/bundles.php
  package.json
  src/Controller/AdminConsultantController.php
  src/Form/ConsultantSearchJobType.php
  symfony.lock
  templates/admin_consultant/index.html.twig
  templates/icons/search.svg
  yarn.lock
Labels: REVIEWED

#147 en tant qu'admin je veux une page listant mes users
  src/Controller/AdminMemberController.php
  templates/admin_membres/index.html.twig
Labels: REVIEWED

#149 en tant qu'admin je veux pouvoir assigner un ou des rôle(s) à mes users
  src/Controller/AdminMemberController.php
  src/Form/UserType.php
  templates/admin_member/_form.html.twig
  templates/admin_member/edit.html.twig
  templates/admin_member/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#148 Fix routes
  config/packages/security.yaml
  src/Controller/AdminJobOfferController.php
  src/Controller/CompanyController.php
  templates/PageCandidate/index.html.twig
  templates/components/_navbar.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  yarn.lock
Labels: REVIEWED

#150 modifs boutton cards
  migrations/Version20230710135046.php
  src/Controller/JobOfferController.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/JobOffer.php
  templates/company/index.html.twig
  templates/components/jobOffer-card.html.twig
  templates/jobOffer/show.html.twig
Labels: REVIEWED

#151 Flash deconnexion
  composer.json
  composer.lock
  src/EventListener/LogoutSubscriber.php
  templates/base.html.twig
Labels: REVIEWED

#152 S06 #43 job offer to candidate
  src/Controller/AdminConsultantController.php
  src/DataFixtures/JobOfferFixtures.php
  templates/admin_consultant/index.html.twig
  templates/admin_consultant/show.html.twig
Labels: REVIEWED, AIMERY'S LABEL, CEDRICK'S LABEL

#154 accès liste membres from admin menu
  templates/components/admin/nav-admin.html.twig
Labels: REVIEWED

#155 commit
  src/Form/UserType.php
  templates/admin_member/edit.html.twig
  templates/admin_membres/index.html.twig
Labels: REVIEWED, CEDRICK'S LABEL

#157 href ajouté
  templates/components/admin/nav-admin.html.twig
Labels: REVIEWED

#156 style + boucle sur formation, experience et skill
  src/Controller/AdminConsultantController.php
  templates/admin_consultant/index.html.twig
  templates/admin_consultant/show.html.twig
  yarn.lock
Labels: REVIEWED

#158 Implémentation rayon des offres
  src/Controller/AdminConsultantController.php
  src/Controller/JobOfferController.php
  src/Entity/JobOfferSearch.php
  src/Form/SearchJobType.php
  src/Repository/JobOfferRepository.php
Labels: REVIEWED, CONFLICTS RESOLVED

#159 Fixt offers
  src/DataFixtures/JobOfferFixtures.php
  src/Form/SearchJobType.php
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#160 Création du Favicon avec logo Externatic
  templates/base.html.twig
Labels: REVIEWED

#161 fix des autorisations isGranted & co
  src/Controller/AdminConsultantController.php
  src/Controller/AdminJobOfferController.php
  src/Controller/ConsultantController.php
  src/Controller/HomeAdminController.php
  templates/company/index.html.twig
  templates/consultant/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#163 el robertito
  templates/components/admin/home.html.twig
Labels: REVIEWED, Capello's label

#162 modifs postulation
  migrations/Version20230713102500.php
  src/Controller/ApplyController.php
  src/Controller/JobOfferController.php
  src/Entity/Candidate.php
  src/Entity/JobOffer.php
  templates/apply/index.html.twig
  templates/components/_navbar.html.twig
  templates/jobOffer/_apply_form.html.twig
  templates/jobOffer/show.html.twig
Labels: READ PLEASE, Capello's label

#166 Récupération adresse du candidat pour calcul radius
  assets/styles/jobOffer.scss
  src/Controller/JobOfferController.php
  src/DataFixtures/CandidateFixtures.php
  src/Entity/JobOfferSearch.php
  src/Form/CandidateType.php
  src/Form/SearchJobType.php
  templates/candidate/profile.html.twig
  templates/icons/camera.svg
  templates/icons/edit.svg
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#165 profil correction
  templates/components/admin/nav-admin.html.twig
Labels: REVIEWED

#167 Fix assets
  assets/images/favicon.png
  templates/base.html.twig
Labels: REVIEWED

#164 entreprise ajout de phone
  migrations/Version20230713093328.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/JobOffer.php
  templates/admin_consultant/index.html.twig
  templates/admin_consultant/show.html.twig
  templates/icons/door.svg
  templates/icons/phone.svg
Labels: REVIEWED, CONFLICTS RESOLVED

#168 modifs style searchbar job
  assets/styles/jobOffer.scss
  src/Form/SearchJobType.php
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#169 modifs
  migrations/Version20230717085207.php
Labels: REVIEWED

#170 Fixed radius progression
  assets/controllers/map_controller.js
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/candidate/profile.html.twig
Labels: REVIEWED

#171 changement de style des cards de jobOffer
  assets/styles/jobOffer.scss
  templates/components/jobOffer-card.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#172 modifs style form
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#174 fixed unrealistic coordinates
  src/DataFixtures/JobOfferFixtures.php
Labels: REVIEWED

#176 fixed default error page including error 500
  templates/bundles/TwigBundle/Exception/error.html.twig
Labels: REVIEWED

#177 Style.fav
  templates/components/jobOffer-card.html.twig
  templates/jobOffer/_favorite_form.html.twig
Labels: REVIEWED

#194 modifs fix
  src/Form/JobOfferType.php
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/show.html.twig
Labels: REVIEWED, JA'S LABEL

#178 modification sur le style du bouton fav sur les cards ainsi qu'un ajo…
  composer.json
  composer.lock
  templates/components/jobOffer-card.html.twig
  templates/jobOffer/_favorite_form.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#196 fix link
  templates/home/index.html.twig
Labels: REVIEWED

#198 Redirect fix
  src/Controller/CandidateController.php
Labels: REVIEWED

#201 Fix profile pic deformed
  templates/candidate/profile.html.twig
Labels: REVIEWED, ZAK'S LABEL

#199 modifs fixtures
  assets/controllers/map_controller.js
  templates/components/jobOffer-card.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#202 fix modifs
  templates/candidate/profile.html.twig
  templates/candidate/show.html.twig
  templates/experience/_delete_form.html.twig
  templates/icons/add.svg
Labels: REVIEWED

#204 Fixed upload et lien vers le fichier
  config/packages/vich_uploader.yaml
  templates/candidate/profile.html.twig
Labels: REVIEWED

#205 Dev to main
  assets/controllers/map_controller.js
  assets/styles/_navbar.scss
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  src/Controller/CandidateController.php
  src/Form/JobOfferType.php
  src/Form/SearchJobType.php
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/show.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/candidate/profile.html.twig
  templates/candidate/show.html.twig
  templates/components/_navbar.html.twig
  templates/components/jobOffer-card.html.twig
  templates/consultant/edit.html.twig
  templates/experience/_delete_form.html.twig
  templates/home/index.html.twig
  templates/icons/add.svg
  templates/jobOffer/_favorite_form.html.twig
Labels: REVIEWED

#206 modifs role
  config/packages/security.yaml
  src/Controller/AdminConsultantController.php
  src/Controller/AdminJobOfferController.php
  src/Controller/CompanyController.php
  src/Controller/HomeAdminController.php
  src/DataFixtures/UserFixtures.php
  templates/company/index.html.twig
  templates/components/_navbar.html.twig
  templates/components/admin/nav-admin.html.twig
Labels: REVIEWED

#208 Fix Button CV
  templates/candidate/profile.html.twig
  templates/icons/edit.svg
  templates/icons/file.svg
Labels: REVIEWED

#197 ajouts footer dans base
  templates/base.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#209 modifs apply
  templates/admin_consultant/show.html.twig
  templates/components/_footer.html.twig
Labels: REVIEWED

#210 Fix-responsive
  templates/candidate/profile.html.twig
Labels: REVIEWED, RUBEN'S LABEL

#211 navbar admin responsive + style, page consultant responsive
  assets/styles/_navbar-admin.scss
  src/Controller/AdminConsultantController.php
  templates/admin_consultant/show.html.twig
  templates/base-admin.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/icons/company.svg
  templates/icons/consultant.svg
  templates/icons/offers.svg
  templates/icons/relationship.svg
Labels: REVIEWED, CONFLICTS RESOLVED

#212 Fix link
  templates/business-card/index.html.twig
Labels: REVIEWED

#216 crud businesCard
  src/Controller/BusinessCardAdminController.php
  src/Form/BusinessCardType.php
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/show.html.twig
  templates/business_card_admin/_delete_form.html.twig
  templates/business_card_admin/_form.html.twig
  templates/business_card_admin/edit.html.twig
  templates/business_card_admin/index.html.twig
  templates/business_card_admin/new.html.twig
  templates/components/admin/nav-admin.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#218 modifs name
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/consultant/edit.html.twig
  templates/consultant/index.html.twig
  templates/icons/businesscard.svg
Labels: REVIEWED

#219 fix txt
  templates/admin_consultant/show.html.twig
Labels: REVIEWED

#220 RESPONSIVE REREREREFAIT ADMIN RELATION POUR LA NIEME FOISgit add .
  templates/admin_consultant/index.html.twig
  templates/admin_consultant/show.html.twig
Labels: REVIEWED

#223 modifs fautes de frappe
  templates/business-card/index.html.twig
Labels: REVIEWED, CEDRICK'S LABEL

#221 modifs
  assets/styles/home.scss
  templates/company/edit.html.twig
  templates/company/home/index.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#224 Flash messages
  src/EventListener/LoginSubscriber.php
  templates/base-admin.html.twig
  templates/candidate/edit.html.twig
Labels: REVIEWED, CORRECTIONS DONE

#226 fix
  templates/components/admin/home.html.twig
Labels: REVIEWED

#227 fix btn Envoyer/retirer
  src/Controller/JobOfferController.php
  src/Entity/Candidate.php
  templates/jobOffer/_apply_form.html.twig
Labels: REVIEWED

#232 Edit candidate3
  src/Controller/CandidateController.php
  templates/candidate/profile.html.twig
Labels: REVIEWED, CORRECTIONS DONE

#233 Add flash messages consultant/candidate
  src/Controller/JobOfferController.php
  src/Controller/PostulationController.php
Labels: REVIEWED, READ PLEASE, REFUS FORMATEUR, ZAK'S LABEL

#234 modifs
  templates/candidate/profile.html.twig
Labels: REVIEWED, AIMERY'S LABEL, CEDRICK'S LABEL, ZAK'S LABEL, JA'S LABEL

#235 Dave Toomaine
  assets/styles/home.scss
  assets/styles/jobOffer.scss
  src/Controller/CandidateController.php
  src/Controller/JobOfferController.php
  src/Controller/PostulationController.php
  src/Entity/Candidate.php
  src/EventListener/LoginSubscriber.php
  templates/admin_consultant/show.html.twig
  templates/apply/index.html.twig
  templates/base-admin.html.twig
  templates/business-card/index.html.twig
  templates/business_card_admin/index.html.twig
  templates/candidate/edit.html.twig
  templates/candidate/profile.html.twig
  templates/company/edit.html.twig
  templates/company/home/index.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/components/admin/home.html.twig
  templates/components/admin/nav-admin.html.twig
  templates/home/index.html.twig
  templates/icons/accept.svg
  templates/icons/cross.svg
  templates/icons/pending.svg
  templates/icons/refuse.svg
  templates/icons/validate.svg
  templates/jobOffer/_apply_form.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: REVIEWED

#238 Style.profil.ja
  templates/admin_jobOffer/show.html.twig
  templates/candidate/profile.html.twig
  templates/icons/edite.svg
Labels: REVIEWED

#240 modifs position footer
  templates/company/home/index.html.twig
Labels: REVIEWED

#241 Fix espace trop grand
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#243 modifs
  src/Form/CandidateType.php
  templates/candidate/edit.html.twig
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#244 add Hue rotate
  assets/styles/jobOffer.scss
Labels: REVIEWED

#248 Add scale
  assets/controllers/map_controller.js
Labels: REVIEWED

#247 Fix admin
  assets/styles/profil.scss
  src/Form/JobOfferType.php
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/show.html.twig
  templates/candidate/profile.html.twig
Labels: REVIEWED, CORRECTIONS DONE

#249 Dev 2 main
  assets/controllers/map_controller.js
  assets/styles/jobOffer.scss
  assets/styles/profil.scss
  src/Form/CandidateType.php
  src/Form/JobOfferType.php
  templates/admin_jobOffer/index.html.twig
  templates/admin_jobOffer/show.html.twig
  templates/candidate/edit.html.twig
  templates/candidate/profile.html.twig
  templates/company/home/index.html.twig
  templates/icons/edite.svg
  templates/jobOffer/index.html.twig
Labels: REVIEWED

#250 fix typo
  templates/company/home/index.html.twig
Labels: REVIEWED, RUBEN'S LABEL

#253 DevToMain
  templates/company/home/index.html.twig
  templates/components/jobOffer-card.html.twig
  templates/icons/refuse.svg
Labels: REVIEWED, RUBEN'S LABEL

#254 modifs
  config/packages/webpack_encore.yaml
Labels: REVIEWED, READ PLEASE

#255 modifs
  templates/candidate/profile.html.twig
Labels: REVIEWED

#257 Dev to main
  config/packages/webpack_encore.yaml
  templates/candidate/profile.html.twig
Labels: REVIEWED
